### ISSUE TITLE
Own prefix

### ISSUE THREAD

**Issue by Puliczek** [rhinobase/hono-rate-limiter#32]
Is it possible to add own prefix to standardHeaders?

I would like to use "draft-6"

```
ratelimit-limit: 15
ratelimit-policy: 15;w=86400
ratelimit-remaining: 0
ratelimit-reset: 81644
```

But add prefix like 'apiname'

```
apiname-ratelimit-limit: 15
apiname-ratelimit-policy: 15;w=86400
apiname-ratelimit-remaining: 0
apiname-ratelimit-reset: 81644
```

Is it possible to change it in handler?

Thanks :)

**Comment by MathurAditya724** [comment]
This is not possible as we are following the draft's RFC, which you can also see here - https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-ratelimit-headers-06#name-ratelimit-header-field-defi

But if you still want to do something like this, you can create a middleware, placed before placing the rate-limiter so that you can run it after the headers have been set. Then you can use the context to modify the headers and return the new response.

**Comment by Puliczek** [comment]
Thank you very much, that makes sense. I will go with the new middleware :)
